## SealedSecret
---
- name: External DNS Setup
  hosts: all
  vars:
    CLUSTER_NAME: aws-virginia-portal-ventas-produccion
    REGION: "us-east-1"

  tasks:
    
    - name: Creating external-dns-deployment.yaml
      template:
        src: external-dns-deployment.j2
        dest: external-dns-deployment.yaml
    
    - name: Setup external dns
      shell: kubectl apply -f external-dns-deployment.yaml
    
    - name: Deleting external-dns-deployment.yaml
      file:
        path: external-dns-deployment.yaml
        state: absent
